import React from 'react';

export const language = {
    en:
    {
        main_display: <><img alt="" style={{ maxWidth: "25px" }} src="img/elements/en.jpg" />{" English (En)"}</>,
        selector: <><img alt="" style={{ maxWidth: "25px" }} src="img/elements/en.jpg" />{" Switch to English (En)"}</>,
        t_home: <>{"HOME"}</>,
        t_introduction: <>{"INTRODUCTION"}</>,
        t_abilities: <>{"ABILITIES"}</>,
        t_features: <>{"FEATURES"}</>,
        t_playground: <>{"PLAYGROUND"}  </>,
        t_welcome: <>{`Welcome \nTo CMM-B Prototype\nThe First of its kind`}</>,
        t_the_change: <>{"The Change My Mind Bot that will litterally, change your mind"}</>,
        t_find: <>{"Find out more!"} </>,
        t_the_making: <>{`The Making of\nCMM-B Prototype`}</>,
        t_it_spell: <>{`It's a Simple Spell But Quite Unbreakable`}</>,
        t_based_on_algo: <>{`Based on the Forward chaining (or forward reasoning) implementation strategy\nfor expert systems, the CMM-B hosts an inference engine that is able to logically\nlink various conditions with associated consequences in between given statements.\nTo provide in the very end a link between your Hypothesis and the provided fact database.`}</>,
        t_know: <>{"Know more!"} </>,
        t_how: <>{`How does CMM-B \nworks? How far can it gets?`}</>,
        t_it_more: <>{`It is more than a machine, less than Human \nit is a Prototype`}</>,
        t_it_much: <>{"It ain't much but it's honest work ... and learning kiddo! "}</>,
        t_based_on_input: <>{`Based on some already fed sentences, CMM-B can provide you a set of argumentation to prove your\ngiven Hypothesis/Conclusion, otherwise you can opt in and provide a sort of input sentences/file\nand it can use them alternatively to the database, however they will be devoured as-well.`}</>,
        t_get: <>{"Get Started Now"}</>,
        t_some: <>{"Some Features that Made CMM-B unique."}</>,
        t_the_b_stands: <>{"The B stands for Bot, not denoting there were any A or C, it's unique"}</>,
        t_optimised: <>{"Optimised Runtime."}</>,
        t_ithandles: <>{" It handles terabytes of data in the backend in the blink of an eye to provide you the finest answers."}</>,
        t_human: <>{"Human-like answers."}</>,
        t_inspired: <>{"Inspired by some poetry and languistic arts, CMM-B can outputs variant answers to the same input."}</>,
        t_bilingual: <>{"Bilingual Bot."}</>,
        t_starting: <>{"Starting with English, French and soon Arabic, you can select your dialog language and it will answer you accordingly."}</>,
        t_laziness: <>{"Laziness Support."}</>,
        t_if: <>{"If you don't feel like writing some input data for the test, you can provide just your Hypothesis and we find the logic ."}</>,
        t_highly: <>{"Highly Recomended"}</>,
        t_swift: <>{"Swift looks, Smooth running, and incoming updates all serving the purpose to enhance CMM-B."}</>,
        t_positive: <>{"Positive Reviews"}</>,
        t_by_our: <>{"By our fellow students, this had a great agreement and postive feedback, want to add your Love?"}</>,
        t_go_ahead: <>{"Go ahead and try"}</>,
        t_made: <>{"Made by the P&R Duo"}</>,
        t_copyright: <>{"Copyright"}</>,
        t_all: <>{"All rights reserved | Made with"}</>,
        t_by: <>{"by"} </>,
        t_cmm: <>{"CMM-B to the Work!"}</>,
        t_here: <>{"Here is the playground for the CMM-B. The Automated mode is toggled "}</>,
        t_on: <>{"On"}</>,
        t_off: <>{"Off"}</>,
        t_turn_it_off: <>{"Turn it off"}</>,
        t_turn_it_on: <>{"Turn it on"}</>,
        t_input_hyp: <>{"Input for Hypothesis to demonstrate,"}</>,
        t_each_line_hyp: <>{"Each Hypothesis should be in a separate line."}</>,
        t_input_conc:"Input you opt to conclude, Each in a separate line.",
        t_each_line_conc: <>{"Each Conclusion should be in a separate line."}</>,
        t_execute: <>{"  Execute"}</>,
        t_cancel: <>{" Cancel!"}</>,
        t_manual: <>{"Manual input for Rules, each rules must match the following syntax:"}<br /><span className="text-muted text-italic">{"*[Cause(s) (comma/logical-word separated)][,/conclusion expression][Consequence(s) comma/logical-word separated]"}</span></>,
        t_or: `Or you can upload a Text file.\nEach line/item must follow the syntax above!`,


    },
    fr:
    {
        main_display: <><img alt="" style={{ maxWidth: "25px" }} src="img/elements/fr.jpg" /> {" Français (Fr)"}</>,
        selector: <><img alt="" style={{ maxWidth: "25px" }} src="img/elements/fr.jpg" /> {" Changez au Français (Fr)"}</>,
        t_home: <>{"ACCUEIL"}</>,
        t_introduction: <>{"INTRODUCTION"}</>,
        t_abilities: <>{"PUISSANCE"}</>,
        t_features: <>{"FONCTIONNALITES"}</>,
        t_playground: <>{"MISE EN MARCHE"}  </>,
        t_welcome: <>{`Bienvenue \nChez CMM-B Prototype\nLe merveilleux`}</>,
        t_the_change: <>{"Le Bot Change My Mind qui va te changer d'avis, ou le renforcer."}</>,
        t_find: <>{"Trouvez de plus!"} </>,
        t_the_making: <>{`La Création de\nCMM-B Prototype`}</>,
        t_it_spell: <>{`La simplicité, c'est la beauté...`}</>,
        t_based_on_algo: <>{`Basé sur les algorithmes de chainage en avant, qui s'agit d'une implémentation pour le systeme des experts. Le Prototype de CMM-B integre cette connaissance afin de démontrer logiquement la cohérence entre une base des faits et un but à démontrer en se basant sur une base de règles fournie.`}</>,
        t_know: <>{"Découvrez plus!"} </>,
        t_how: <>{`Comment CMM-B \nfonctionne? Ses limites?`}</>,
        t_it_more: <>{`Plus qu'une machine et Moins qu'un Cyborg \nIl est un Prototype`}</>,
        t_it_much: <>{"La connaissance n'est jamais un don, soit on sait, soit on apprend! "}</>,
        t_based_on_input: <>{`Basé sur quelques phrases insérées, CMM-B peut vous servit une argumatation prouvant votre conclusion à partir de votre hypothèse. Sinon, vous pouvez activer la façon automatique qui essaierai de cherchez des règles dans notre propre base de données qui s'alimente de toute nouvelles.`}</>,
        t_get: <>{"Allons-y!"}</>,
        t_some: <>{"Quelques fonctionnalités de CMM-B."}</>,
        t_the_b_stands: <>{"Le B s'agit d'une abrv. de 'Bot', et non pas l'ordre de construction,il est unique"}</>,
        t_optimised: <>{"Execution Optimale."}</>,
        t_ithandles: <>{" Des térabytes sont parcourus instantanément pour vous servir les resultats les plus fines."}</>,
        t_human: <>{"Réponse humainitaire!."}</>,
        t_inspired: <>{"Inspiré par la litérature et quelques expressions linguistiques, CMM-B sert d'illégante résultats."}</>,
        t_bilingual: <>{"Bot Bilingue."}</>,
        t_starting: <>{"Pour l'instant il excelle l'Anglais et le Français et prochainement L'Arabe,Choisissez votre langue."}</>,
        t_laziness: <>{"Vive La paresse."}</>,
        t_if: <>{"Si vous voulez, vous pouvez activer le service automatique des entrés sans rien écrire!"}</>,
        t_highly: <>{"Recomendation Superbe"}</>,
        t_swift: <>{"Look Charmant et Design magnifique avec tout les updates en route tout à votre service."}</>,
        t_positive: <>{"Feedback Positif"}</>,
        t_by_our: <>{"Par nos collègues et partenaire, ce petit prototype a eu leur gratitute, Nous vous attendons?"}</>,
        t_go_ahead: <>{"Vas-y nous contactez!"}</>,
        t_made: <>{"Réalisé par le Duo P&R"}</>,
        t_copyright: <>{"Droit de Copie"}</>,
        t_all: <>{"Tout droits reservés | Crée avec "}</>,
        t_by: <>{"par"} </>,
        t_cmm: <>{"CMM-B to the Work!"}</>,
        t_here: <>{"Ici la Mise en Marche de CMM-B.Le Mode Automatique est "}</>,
        t_on: <>{"Actif"}</>,
        t_off: <>{"Désactivé"}</>,
        t_turn_it_off: <>{"Activez-le"}</>,
        t_turn_it_on: <>{"Désactivez"}</>,
        t_input_hyp: <>{"Entré de les hypothèses de la base des faits ,"}</>,
        t_each_line_hyp: <>{"Chaque hypothèse doit être dans une ligne séparé."}</>,
        t_input_conc:"But(s) de la démonstration.",
        t_each_line_conc: <>{"Chaque but doit être dans une ligne séparé."}</>,
        t_execute: <>{"  Executez!"}</>,
        t_cancel: <>{" Effacer!"}</>,
        t_manual: <>{"Entré manuelle, Chaque règle doit respecter le syntaxe suivant:"}<br /><span className="text-muted text-italic">{"*[Cause(s) (séparé par des virgules/ expression logique)][point/expression de conclusion][séparé par des virgules/ expression logique]"}</span></>,
        t_or: `Ou vous pouvez héberger votre fichier Text (.txt).\nChaque ligne/items doit respecter le syntaxe ci-dessus!`,

    }
}
